telegram_token: ""
openai_api_key: ""
openai_api_base: null
allowed_telegram_usernames: []
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512"
enable_message_streaming: true
new_dialog_timeout: 0.1
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006

OPENAI_COMPLETION_OPTIONS:
  temperature: 0.7
  max_tokens: 1000
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  request_timeout: 60.0
